// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package cgx.proto;

public final class ProtoLogin {
  private ProtoLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cgx.proto.ProtoLogin.internal_static_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cgx.proto.ProtoLogin.internal_static_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cgx.proto.ProtoLogin.Login.class, cgx.proto.ProtoLogin.Login.Builder.class);
    }

    public interface C2SOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Login.C2S)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 cmd = 1;</code>
       */
      int getCmd();

      /**
       * <code>int64 playerId = 2;</code>
       */
      long getPlayerId();
    }
    /**
     * Protobuf type {@code Login.C2S}
     */
    public  static final class C2S extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Login.C2S)
        C2SOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use C2S.newBuilder() to construct.
      private C2S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private C2S() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private C2S(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                cmd_ = input.readInt32();
                break;
              }
              case 16: {

                playerId_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cgx.proto.ProtoLogin.internal_static_Login_C2S_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cgx.proto.ProtoLogin.internal_static_Login_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cgx.proto.ProtoLogin.Login.C2S.class, cgx.proto.ProtoLogin.Login.C2S.Builder.class);
      }

      public static final int CMD_FIELD_NUMBER = 1;
      private int cmd_;
      /**
       * <code>int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }

      public static final int PLAYERID_FIELD_NUMBER = 2;
      private long playerId_;
      /**
       * <code>int64 playerId = 2;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (cmd_ != 0) {
          output.writeInt32(1, cmd_);
        }
        if (playerId_ != 0L) {
          output.writeInt64(2, playerId_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (cmd_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, cmd_);
        }
        if (playerId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, playerId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cgx.proto.ProtoLogin.Login.C2S)) {
          return super.equals(obj);
        }
        cgx.proto.ProtoLogin.Login.C2S other = (cgx.proto.ProtoLogin.Login.C2S) obj;

        if (getCmd()
            != other.getCmd()) return false;
        if (getPlayerId()
            != other.getPlayerId()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd();
        hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPlayerId());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.C2S parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cgx.proto.ProtoLogin.Login.C2S prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Login.C2S}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Login.C2S)
          cgx.proto.ProtoLogin.Login.C2SOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cgx.proto.ProtoLogin.internal_static_Login_C2S_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cgx.proto.ProtoLogin.internal_static_Login_C2S_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cgx.proto.ProtoLogin.Login.C2S.class, cgx.proto.ProtoLogin.Login.C2S.Builder.class);
        }

        // Construct using cgx.proto.ProtoLogin.Login.C2S.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          cmd_ = 0;

          playerId_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cgx.proto.ProtoLogin.internal_static_Login_C2S_descriptor;
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.C2S getDefaultInstanceForType() {
          return cgx.proto.ProtoLogin.Login.C2S.getDefaultInstance();
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.C2S build() {
          cgx.proto.ProtoLogin.Login.C2S result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.C2S buildPartial() {
          cgx.proto.ProtoLogin.Login.C2S result = new cgx.proto.ProtoLogin.Login.C2S(this);
          result.cmd_ = cmd_;
          result.playerId_ = playerId_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cgx.proto.ProtoLogin.Login.C2S) {
            return mergeFrom((cgx.proto.ProtoLogin.Login.C2S)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cgx.proto.ProtoLogin.Login.C2S other) {
          if (other == cgx.proto.ProtoLogin.Login.C2S.getDefaultInstance()) return this;
          if (other.getCmd() != 0) {
            setCmd(other.getCmd());
          }
          if (other.getPlayerId() != 0L) {
            setPlayerId(other.getPlayerId());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cgx.proto.ProtoLogin.Login.C2S parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cgx.proto.ProtoLogin.Login.C2S) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int cmd_ ;
        /**
         * <code>int32 cmd = 1;</code>
         */
        public int getCmd() {
          return cmd_;
        }
        /**
         * <code>int32 cmd = 1;</code>
         */
        public Builder setCmd(int value) {
          
          cmd_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 cmd = 1;</code>
         */
        public Builder clearCmd() {
          
          cmd_ = 0;
          onChanged();
          return this;
        }

        private long playerId_ ;
        /**
         * <code>int64 playerId = 2;</code>
         */
        public long getPlayerId() {
          return playerId_;
        }
        /**
         * <code>int64 playerId = 2;</code>
         */
        public Builder setPlayerId(long value) {
          
          playerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 playerId = 2;</code>
         */
        public Builder clearPlayerId() {
          
          playerId_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Login.C2S)
      }

      // @@protoc_insertion_point(class_scope:Login.C2S)
      private static final cgx.proto.ProtoLogin.Login.C2S DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cgx.proto.ProtoLogin.Login.C2S();
      }

      public static cgx.proto.ProtoLogin.Login.C2S getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<C2S>
          PARSER = new com.google.protobuf.AbstractParser<C2S>() {
        @java.lang.Override
        public C2S parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<C2S> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<C2S> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public cgx.proto.ProtoLogin.Login.C2S getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface S2COrBuilder extends
        // @@protoc_insertion_point(interface_extends:Login.S2C)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.Player player = 1;</code>
       */
      boolean hasPlayer();
      /**
       * <code>.Player player = 1;</code>
       */
      cgx.proto.ProtoPlayer.Player getPlayer();
      /**
       * <code>.Player player = 1;</code>
       */
      cgx.proto.ProtoPlayer.PlayerOrBuilder getPlayerOrBuilder();
    }
    /**
     * Protobuf type {@code Login.S2C}
     */
    public  static final class S2C extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Login.S2C)
        S2COrBuilder {
    private static final long serialVersionUID = 0L;
      // Use S2C.newBuilder() to construct.
      private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private S2C() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private S2C(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                cgx.proto.ProtoPlayer.Player.Builder subBuilder = null;
                if (player_ != null) {
                  subBuilder = player_.toBuilder();
                }
                player_ = input.readMessage(cgx.proto.ProtoPlayer.Player.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(player_);
                  player_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cgx.proto.ProtoLogin.internal_static_Login_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cgx.proto.ProtoLogin.internal_static_Login_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cgx.proto.ProtoLogin.Login.S2C.class, cgx.proto.ProtoLogin.Login.S2C.Builder.class);
      }

      public static final int PLAYER_FIELD_NUMBER = 1;
      private cgx.proto.ProtoPlayer.Player player_;
      /**
       * <code>.Player player = 1;</code>
       */
      public boolean hasPlayer() {
        return player_ != null;
      }
      /**
       * <code>.Player player = 1;</code>
       */
      public cgx.proto.ProtoPlayer.Player getPlayer() {
        return player_ == null ? cgx.proto.ProtoPlayer.Player.getDefaultInstance() : player_;
      }
      /**
       * <code>.Player player = 1;</code>
       */
      public cgx.proto.ProtoPlayer.PlayerOrBuilder getPlayerOrBuilder() {
        return getPlayer();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (player_ != null) {
          output.writeMessage(1, getPlayer());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (player_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getPlayer());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cgx.proto.ProtoLogin.Login.S2C)) {
          return super.equals(obj);
        }
        cgx.proto.ProtoLogin.Login.S2C other = (cgx.proto.ProtoLogin.Login.S2C) obj;

        if (hasPlayer() != other.hasPlayer()) return false;
        if (hasPlayer()) {
          if (!getPlayer()
              .equals(other.getPlayer())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasPlayer()) {
          hash = (37 * hash) + PLAYER_FIELD_NUMBER;
          hash = (53 * hash) + getPlayer().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cgx.proto.ProtoLogin.Login.S2C parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cgx.proto.ProtoLogin.Login.S2C prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Login.S2C}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Login.S2C)
          cgx.proto.ProtoLogin.Login.S2COrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cgx.proto.ProtoLogin.internal_static_Login_S2C_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cgx.proto.ProtoLogin.internal_static_Login_S2C_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cgx.proto.ProtoLogin.Login.S2C.class, cgx.proto.ProtoLogin.Login.S2C.Builder.class);
        }

        // Construct using cgx.proto.ProtoLogin.Login.S2C.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (playerBuilder_ == null) {
            player_ = null;
          } else {
            player_ = null;
            playerBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cgx.proto.ProtoLogin.internal_static_Login_S2C_descriptor;
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.S2C getDefaultInstanceForType() {
          return cgx.proto.ProtoLogin.Login.S2C.getDefaultInstance();
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.S2C build() {
          cgx.proto.ProtoLogin.Login.S2C result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public cgx.proto.ProtoLogin.Login.S2C buildPartial() {
          cgx.proto.ProtoLogin.Login.S2C result = new cgx.proto.ProtoLogin.Login.S2C(this);
          if (playerBuilder_ == null) {
            result.player_ = player_;
          } else {
            result.player_ = playerBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cgx.proto.ProtoLogin.Login.S2C) {
            return mergeFrom((cgx.proto.ProtoLogin.Login.S2C)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cgx.proto.ProtoLogin.Login.S2C other) {
          if (other == cgx.proto.ProtoLogin.Login.S2C.getDefaultInstance()) return this;
          if (other.hasPlayer()) {
            mergePlayer(other.getPlayer());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cgx.proto.ProtoLogin.Login.S2C parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cgx.proto.ProtoLogin.Login.S2C) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private cgx.proto.ProtoPlayer.Player player_;
        private com.google.protobuf.SingleFieldBuilderV3<
            cgx.proto.ProtoPlayer.Player, cgx.proto.ProtoPlayer.Player.Builder, cgx.proto.ProtoPlayer.PlayerOrBuilder> playerBuilder_;
        /**
         * <code>.Player player = 1;</code>
         */
        public boolean hasPlayer() {
          return playerBuilder_ != null || player_ != null;
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public cgx.proto.ProtoPlayer.Player getPlayer() {
          if (playerBuilder_ == null) {
            return player_ == null ? cgx.proto.ProtoPlayer.Player.getDefaultInstance() : player_;
          } else {
            return playerBuilder_.getMessage();
          }
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public Builder setPlayer(cgx.proto.ProtoPlayer.Player value) {
          if (playerBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            player_ = value;
            onChanged();
          } else {
            playerBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public Builder setPlayer(
            cgx.proto.ProtoPlayer.Player.Builder builderForValue) {
          if (playerBuilder_ == null) {
            player_ = builderForValue.build();
            onChanged();
          } else {
            playerBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public Builder mergePlayer(cgx.proto.ProtoPlayer.Player value) {
          if (playerBuilder_ == null) {
            if (player_ != null) {
              player_ =
                cgx.proto.ProtoPlayer.Player.newBuilder(player_).mergeFrom(value).buildPartial();
            } else {
              player_ = value;
            }
            onChanged();
          } else {
            playerBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public Builder clearPlayer() {
          if (playerBuilder_ == null) {
            player_ = null;
            onChanged();
          } else {
            player_ = null;
            playerBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public cgx.proto.ProtoPlayer.Player.Builder getPlayerBuilder() {
          
          onChanged();
          return getPlayerFieldBuilder().getBuilder();
        }
        /**
         * <code>.Player player = 1;</code>
         */
        public cgx.proto.ProtoPlayer.PlayerOrBuilder getPlayerOrBuilder() {
          if (playerBuilder_ != null) {
            return playerBuilder_.getMessageOrBuilder();
          } else {
            return player_ == null ?
                cgx.proto.ProtoPlayer.Player.getDefaultInstance() : player_;
          }
        }
        /**
         * <code>.Player player = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            cgx.proto.ProtoPlayer.Player, cgx.proto.ProtoPlayer.Player.Builder, cgx.proto.ProtoPlayer.PlayerOrBuilder> 
            getPlayerFieldBuilder() {
          if (playerBuilder_ == null) {
            playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                cgx.proto.ProtoPlayer.Player, cgx.proto.ProtoPlayer.Player.Builder, cgx.proto.ProtoPlayer.PlayerOrBuilder>(
                    getPlayer(),
                    getParentForChildren(),
                    isClean());
            player_ = null;
          }
          return playerBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Login.S2C)
      }

      // @@protoc_insertion_point(class_scope:Login.S2C)
      private static final cgx.proto.ProtoLogin.Login.S2C DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cgx.proto.ProtoLogin.Login.S2C();
      }

      public static cgx.proto.ProtoLogin.Login.S2C getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<S2C>
          PARSER = new com.google.protobuf.AbstractParser<S2C>() {
        @java.lang.Override
        public S2C parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<S2C> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<S2C> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public cgx.proto.ProtoLogin.Login.S2C getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cgx.proto.ProtoLogin.Login)) {
        return super.equals(obj);
      }
      cgx.proto.ProtoLogin.Login other = (cgx.proto.ProtoLogin.Login) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cgx.proto.ProtoLogin.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cgx.proto.ProtoLogin.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cgx.proto.ProtoLogin.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cgx.proto.ProtoLogin.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cgx.proto.ProtoLogin.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login)
        cgx.proto.ProtoLogin.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cgx.proto.ProtoLogin.internal_static_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cgx.proto.ProtoLogin.internal_static_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cgx.proto.ProtoLogin.Login.class, cgx.proto.ProtoLogin.Login.Builder.class);
      }

      // Construct using cgx.proto.ProtoLogin.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cgx.proto.ProtoLogin.internal_static_Login_descriptor;
      }

      @java.lang.Override
      public cgx.proto.ProtoLogin.Login getDefaultInstanceForType() {
        return cgx.proto.ProtoLogin.Login.getDefaultInstance();
      }

      @java.lang.Override
      public cgx.proto.ProtoLogin.Login build() {
        cgx.proto.ProtoLogin.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cgx.proto.ProtoLogin.Login buildPartial() {
        cgx.proto.ProtoLogin.Login result = new cgx.proto.ProtoLogin.Login(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cgx.proto.ProtoLogin.Login) {
          return mergeFrom((cgx.proto.ProtoLogin.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cgx.proto.ProtoLogin.Login other) {
        if (other == cgx.proto.ProtoLogin.Login.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cgx.proto.ProtoLogin.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cgx.proto.ProtoLogin.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Login)
    }

    // @@protoc_insertion_point(class_scope:Login)
    private static final cgx.proto.ProtoLogin.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cgx.proto.ProtoLogin.Login();
    }

    public static cgx.proto.ProtoLogin.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cgx.proto.ProtoLogin.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_C2S_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_C2S_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_S2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\032\014player.proto\"M\n\005Login\032$\n\003" +
      "C2S\022\013\n\003cmd\030\001 \001(\005\022\020\n\010playerId\030\002 \001(\003\032\036\n\003S2" +
      "C\022\027\n\006player\030\001 \001(\0132\007.PlayerB\027\n\tcgx.protoB" +
      "\nProtoLoginb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cgx.proto.ProtoPlayer.getDescriptor(),
        }, assigner);
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new java.lang.String[] { });
    internal_static_Login_C2S_descriptor =
      internal_static_Login_descriptor.getNestedTypes().get(0);
    internal_static_Login_C2S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_C2S_descriptor,
        new java.lang.String[] { "Cmd", "PlayerId", });
    internal_static_Login_S2C_descriptor =
      internal_static_Login_descriptor.getNestedTypes().get(1);
    internal_static_Login_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_S2C_descriptor,
        new java.lang.String[] { "Player", });
    cgx.proto.ProtoPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
